- name: create chrome source list
  become: true
  copy:
    content: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    dest: /etc/apt/sources.list.d/google-chrome.list

- name: add google signing key
  become: true
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: install google chrome stable
  become: true
  apt:
    force_apt_get: true
    name: google-chrome-stable
    update_cache: true
