- name: install system ruby
  become: true
  apt:
    force_apt_get: yes
    name: ruby

- name: install rbenv & ruby
  shell: |
    export PATH=$HOME/.rbenv/bin:$PATH 
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
    rbenv install 2.6.4
    rbenv global 2.6.4
  args:
    warn: false
    executable: /bin/bash
    creates: $HOME/.rbenv
