- name: install sdkman
  shell: curl -s https://get.sdkman.io | bash
  args:
    warn: false
    creates: $HOME/.sdkman

- name: install java 11.0.2
  shell: |
    export SDKMAN_DIR="$HOME/.sdkman"
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install java 11.0.2-open
  args:
    executable: /bin/bash
    creates: $HOME/.sdkman/candidates/java/11.0.2-open/

- name: make java 11.0.2 as default
  shell: |
    export SDKMAN_DIR="$HOME/.sdkman"
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk default java 11.0.2-open
  args:
    executable: /bin/bash

- name: install Maven 3.5.4
  shell: |
    export SDKMAN_DIR="$HOME/.sdkman"
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install maven 3.5.4
    sdk default maven 3.5.4
  args:
    executable: /bin/bash
    creates: $HOME/.sdkman/candidates/maven/3.5.4/

- name: install Gradle 3.5.1
  shell: |
    export SDKMAN_DIR="$HOME/.sdkman"
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install gradle 3.5.1
    sdk default gradle 3.5.1
  args:
    executable: /bin/bash
    creates: $HOME/.sdkman/candidates/gradle/3.5.1/

- name: install Kotlin 1.3.50
  shell: |
    export SDKMAN_DIR="$HOME/.sdkman"
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install kotlin 1.3.50
    sdk default kotlin 1.3.50
  args:
    executable: /bin/bash
    creates: $HOME/.sdkman/candidates/kotlin/1.3.50/



