- name: install snap packages
  become: true
  snap:
    name:
      - slack
      - postman
      - intellij-idea-ultimate
      - goland
      - pycharm-professional
      - shell2http
    classic: yes

