- name: make sure projects folder exists
  file:
    path: $HOME/projects
    state: directory

- name: install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: $HOME/.vim/bundle/Vundle.vim

- name: install powerline-status
  shell: $HOME/anaconda2/bin/conda install -c conda-forge -y powerline-status
  args:
    executable: /bin/bash
    creates: $HOME/anaconda2/lib/python2.7/site-packages/powerline/

- name: Link dot files
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"
