- name: download anaconda2
  get_url:
    url: https://repo.anaconda.com/archive/Anaconda2-2019.07-Linux-x86_64.sh
    dest: /tmp/anaconda2.sh
    mode: '0755'

- name: install anaconda2
  shell: bash /tmp/anaconda2.sh -b -p $HOME/anaconda2
  args:
    creates: $HOME/anaconda2

- name: configure anaconda2
  shell: |
    eval "$($HOME/anaconda2/bin/conda shell.bash hook)"
    conda init
    conda config --set auto_activate_base false

