- name: Download virtualbox 5.2.32
  get_url:
    url: https://download.virtualbox.org/virtualbox/5.2.32/virtualbox-5.2_5.2.32-132073~Ubuntu~bionic_amd64.deb
    dest: /tmp/virtualbox-5.2_5.2.32-132073.deb

- name: Install virtualbox
  become: true
  expect:
    command: apt install -y /tmp/virtualbox-5.2_5.2.32-132073.deb
    timeout: 900
    creates: /usr/bin/virtualbox
    responses:
      (.*)Do you want to continue?(.*): 'Y'

- name: Fix any broken package dependencies
  become: true
  shell: apt-get install -f

